// styles
import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

// nextjs internal
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

// web3 libs
import { WagmiConfig } from "wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";

// services, context modules
import Navbar from "@/components/shared/Navbar";
import { ApplicationDetailContextProvider } from "@/context/ApplicationDetailContext";
import { chainData, wagmiConfigData } from "@/services/wagmi";
import { TRPCReactProvider } from "@/services/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <WagmiConfig config={wagmiConfigData}>
          <RainbowKitProvider chains={chainData}>
            <ApplicationDetailContextProvider>
              <TRPCReactProvider cookies={cookies().toString()}>
                <Navbar />
                <main className="px-6 md:px-0">{children}</main>
              </TRPCReactProvider>
            </ApplicationDetailContextProvider>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
